### PR TITLE
feat: change homepage button design#2713

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
Resolves issue: #2713 

Screenshot:-

Simulator Screen Shot - iPhone 11 - 2020-11-18 at 18 36 10

Alignment of text and color of plus button are different from expected image

### CODE REVIEW

**Comment by zxxma** [comment]
Just some little ajustements & optimization on icons, and it's ok!
Icons must be centered & sized like this.
Capture_decran_2020-11-18_a_14 25 20

**Comment by sakul-budhathoki** [comment]
Latest Screenshot:-

**Comment by zxxma** [comment]
I think we'll need to improve the BackgroundBlur, which is too grey.
We think we need to reduce opacity, and give a little blue effect on the Blur.

I put the expected screen here to compare : 
home-v5 1 Copy 2

**Comment by sakul-budhathoki** [comment]
Latest screenshot:- 
Simulator Screen Shot - iPhone 11 - 2020-11-19 at 11 31 45

**Comment by sakul-budhathoki** [comment]
Latest screenshot:- 
Simulator Screen Shot - iPhone 11 - 2020-11-19 at 18 09 17

**Comment by zxxma** [comment]
LGTM 👍

**Review by clegirar — APPROVED** [review]
LGTM 👍

**Comment by n0izn0iz** [comment]
@sakul-budhathoki 
please pass the DCO check so we can merge

you can see instructions for it by clicking the "Details" link in github

for this PR it's
`git rebase HEAD~10 --signoff`
`git push --force-with-lease origin feat/change-homepage-button-design#2713`

**Review by n0izn0iz — APPROVED** [review]
lgtm

**Comment by sakul-budhathoki** [comment]
Found transition issue after merging with master, due to PR #2754 . 
In android, after navigating to New Group/ Scan and returning back, bottom box is hidden, and can't toggle. So, I couldn't found other way to fix this issue.

So, I have removed route config of HomeModal, and used it directly as a component.

Transition of Modal open and close:- 

Screen Recording 2020-11-24 at 3 46 37 PM

**Comment by clegirar** [comment]
No problem for remove route config of `HomeModal` 👍 
If we remove it like a screen we can remove the type of this screen in `navigation/types.ts`

**Pull request merged**
