### PR TITLE
 feat: image view swipe out

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
Closes: https://github.com/berty/bugs/issues/125

### CODE REVIEW

**Review by n0izn0iz — APPROVED** [review]
lgtm

**Comment by n0izn0iz** [comment]
the translation behavior is not very usable though (cc @zxxma)

**Comment by sakul-budhathoki** [comment]
Okay. I will fix it.

**Comment by zxxma** [comment]
LGTM 👍

**Comment by zxxma** [comment]
LGTM 👍 
Just a little note : 
There is a little latence when we swipe "out" of full screen mode, during 1 sec the pic is locked before finish the exit.
It could be optimize in the future.

**Pull request merged**
