### PR TITLE
navigation transition

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
Issues Link: #2614 

Changes: - 
- Replaced `react-native-screens/native-stack` by `@react-navigation/native`
- Applied custom transition 
- Removed ModalNavigation and used similar fade transition effect for modals
- Removed RequestSent component and it's navigation

navigation-custom

### CODE REVIEW

**Comment by clegirar** [comment]
For the `RequestSent` screen, we used it in some last versions of Berty but the changes have meant that it's no longer used, so i can do a PR if you want for delete all of this ? Else you can delete screen type and the stack in the navigation, and the component
I have hesitated to keep it if in the short term future we would need it but i think we can delete it 👍

**Comment by zxxma** [comment]
Nice job, looks neat.
LGTM 👍

**Review by n0izn0iz — APPROVED** [review]
code lvgtm :D

**Comment by n0izn0iz** [comment]
@sakul-budhathoki please rebase and pass CI

**Pull request merged**
