### PR TITLE
feat: pressable avatar images

### PR DESCRIPTION
**Pull request by sakul-budhathoki**
Signed-off-by: Sakul <sakulbudhathoki977@gmail.com>

### CODE REVIEW

**Review by n0izn0iz — APPROVED** [review]
LGTM (code review)

**Comment by zxxma** [comment]
Looks like it doesn't work, or maybe not understood "where" is pressable?
(not working in a Group conversation)

**Comment by sakul-budhathoki** [comment]
Hi @zxxma . I understand the problem, I will update it and let you know.

**Review by clegirar — APPROVED** [review]
Code LGTM 👍

**Comment by zxxma** [comment]
Problem detected, code looks ok, but it's still not clickable in the app:
image

Same in the Group Settings or in Conversation, when we press, it doesn't work.

**Comment by sakul-budhathoki** [comment]
For now it will be clickable if it is an image, above shown avatar is actually a text inside a circle. I will create a separate view to show this kind of avatar.

**Comment by zxxma** [comment]
You're right, my bad!
LGTM 👍

**Pull request merged**
