### PR TITLE
feat: Implement Multipeer Connectivity driver

### PR DESCRIPTION
**Pull request by D4ryl00**
* [x] Multipeer Connectivity driver implementation
* [x] Integration with v1 of berty
* [ ] Fix bug on cli mode

### CODE REVIEW

**Comment by D4ryl00** [comment]
I'm proud of share this screenshot, my first communication between two devices with `Multipeer Connectivity` :)))
Simulator Screen Shot - iPhone 8 - 2020-04-07 at 15 08 32

**Comment by D4ryl00** [comment]
I've just read that on MacOS, Multipeer Connectivity browsering (aka find nearby devices) doesn't work over Bluetooth !!!
```
MCNearbyServiceBrowser

Searches (by service type) for services offered by nearby devices using infrastructure Wi-Fi, peer-to-peer Wi-Fi, and Bluetooth (in iOS) or Ethernet (in macOS and tvOS), and provides the ability to easily invite those devices to a Multipeer Connectivity session (MCSession).
```
Source: https://developer.apple.com/documentation/multipeerconnectivity/mcnearbyservicebrowser

**Comment by momack2** [comment]
It's happening!!!

**Comment by aeddi** [comment]
I am actively working on a solution to launch a MultipeerConnectivity driver from a CLI app (Berty daemon, IPFS command tool, etc...).

Since this PR only concerns the Berty v1, we can merge it as is (only works on mobile) while waiting for my work to be completed on the driver.

**Comment by D4ryl00** [comment]
I've just test it, app doesn't crash either on mobile or on cli. So I'm going to merge this PR.

**Pull request merged**
