### PR TITLE
chore: Updated IPFS to v0.7.0

### PR DESCRIPTION
**Pull request by Jorropo**
`go.mod` temporary replace can be removed once ipld/go-car#34 is merged and released.

### CODE REVIEW

**Review by moul — CHANGES_REQUESTED** [review]
missing a `make depaware.generate`

**Comment by Jorropo** [comment]
> missing a `make depaware.generate`
@moul 

Fixed :) (I'll add a depaware check to the CI if that not too time costy)

**Comment by moul** [comment]
> Fixed :) (I'll add a depaware check to the CI if that not too time costy)

no, please don't, it will make the development process harder for not so much

I just want the command to be run each time we make massive dependency bumps

**Comment by Jorropo** [comment]
> no, please don't
@moul 

too late :D yes I see, I havn't thinked of that.

**Review by moul — APPROVED** [review]

**Pull request merged**
