### PR TITLE
fix: play sound notifications depending on notif setting

### PR DESCRIPTION
**Pull request by clegirar**
Signed-off-by: clegirar <clemntgirard@gmail.com>

### CODE REVIEW

**Review by n0izn0iz — CHANGES_REQUESTED** [review]
I would prefer that we extend `playSound` in the context and bind the option there
If not, please keep the previous interface and use if statement at call sites

**Review by n0izn0iz — APPROVED** [review]
LGTM

**Comment by zxxma** [comment]
Still ringing on real devices (silence mode: on) :
- on Beta Bot notifications at launch
- on every msg notifications

**Comment by zxxma** [comment]
LGTM 👍  fixed 🔉  & 🔇  :)

**Pull request merged**
