### PR TITLE
fix(messenger): fix main modal and QR scanner sizing

### PR DESCRIPTION
**Pull request by ekelen**
Just quick fixes to remove blocking responsiveness issues (i.e. can't access some interactive UI element).

- QR scanner now always fits on screen
- Main modal is dismissable and interactive on short or landscape screen
- QR scan page is scrollable for access to manual deeplink add form

Related to #1852

### CODE REVIEW

**Comment by moul** [comment]
> QR scanner now always fits on screen

yes it fits, but we are about 10px missing to be able to read the text below on ipad :)

**Comment by moul** [comment]
I've added on discord (on e-meeting-note) a quick video about how it feels on iPad

**Comment by moul** [comment]
btw, except those bugs, the experience is much greater :)

**Comment by ekelen** [comment]
I'm going to add large screen support for this, as there are other situations where we need it. (basically anywhere that adds conditional scroll on landscape – scroll function should be removed if it's landscape on large screen).

**Pull request merged**
