### PR TITLE
Add additional quote

### PR DESCRIPTION
**Pull request by saivishwak**
Add additional quotes related to Berty.

### CODE REVIEW

**Comment by jefft0** [comment]
Hello @saivishwak . Can you please resolve the DCO check as shown above? (Need "Signed-off-by".)

**Comment by aeddi** [comment]
Related to #1829

**Comment by jefft0** [comment]
Hello @saivishwak . Please see the comment above about resolving the DCO check. Otherwise, this issue will be closed as inactive in 14 days.

**Comment by saivishwak** [comment]
Hey Jeff,

Hope you are doing great.

Will look into it. Sorry for the delay.

Thanks and Regards
Sai Vishwak K

**Comment by saivishwak** [comment]
Hi @jefft0 ,

I have resolved the DCO check.

Thank You

**Comment by jefft0** [comment]
Thank you @saivishwak . We will review it.

**Pull request merged**
