### PR TITLE
fix: pause QR code scanner

### PR DESCRIPTION
**Pull request by JohnBerd**
QR code gets hidden after a QR code scanning
QR codes can successfully be scanned several times

### CODE REVIEW

**Comment by n0izn0iz** [comment]
I'm not sure creating a reducer for this is the good tool, can't this be done with the navigation blur/focus hooks?

**Comment by JohnBerd** [comment]
> I'm not sure creating a reducer for this is the good tool, can't this be done with the navigation blur/focus hooks?

Without reducer, the solution remaining would be to pass a callback to route params when navigating to ManageDeepLink component. If it seems to be a better solution for you I can go for it :)

**Review by n0izn0iz — APPROVED** [review]
code LGTM

**Comment by clegirar** [comment]
Test LGTM 👍

**Comment by JohnBerd** [comment]
fix #3393, #3447

**Pull request merged**
