### PR TITLE
fix: android ui issues

### PR DESCRIPTION
**Pull request by sakul-budhathoki**

### CODE REVIEW

**Review by n0izn0iz — APPROVED** [review]
LGTM, did not test

**Comment by zxxma** [comment]
Still have some keyboards problem like this:
(This screen is when I click into the "input nickname" during Onboarding)
 
https://shake-attachments-production.s3.amazonaws.com/f15ed613-65cd-47f4-8ca6-c85dce23f8e8/c0a77fce-8962-437b-af56-561542df067c/screenshot.jpg

**Review by clegirar — APPROVED** [review]
Code LGTM 👍

**Comment by zxxma** [comment]
Some little bugs detected, but good job on main problems!
Let's merge it an work on details after :)
Good job @sakul-budhathoki 👍

**Pull request merged**
