### PR TITLE
feat: create navigation swipe wrapper

### PR DESCRIPTION
**Pull request by ekelen**
- Adds in-house gesture-responding wrappers for screens to enable/improve React-Navigation swipe behavior
- Adds hitSlop area to icons in screen headers to make back arrow easier to press (though maybe we should just remove back arrows altogether on mobile)

### CODE REVIEW

**Review by Jorropo — APPROVED** [review]
LGTM.
Fix : #2327

**Comment by ekelen** [comment]
> LGTM.
> Fix : #2327

Thanks for opening that. I still need to test a few more times since we have some horizontal gesture responders that I don't want to break with this wrapper :)

**Comment by Jorropo** [comment]
> > LGTM.
> > Fix : #2327
> 
> Thanks for opening that. I still need to test a few more times since we have some horizontal gesture responders that I don't want to break with this wrapper :)

ok no problem I can wait (dev tools are no longer accessible but that not crucial for me RN), still thx for fixing this

**Comment by ekelen** [comment]
> > > LGTM.
> > > Fix : #2327
> > 
> > 
> > Thanks for opening that. I still need to test a few more times since we have some horizontal gesture responders that I don't want to break with this wrapper :)
> 
> ok no problem I can wait (dev tools are no longer accessible but that not crucial for me RN), still thx for fixing this

On master or did you check out this PR? I removed the swipe wrapper yesterday as a hotfix, so behavior should back to normal (i.e. no problems with vertical scroll).

**Comment by Jorropo** [comment]
> 
> 
> > > > LGTM.
> > > > Fix : #2327
> > > 
> > > 
> > > Thanks for opening that. I still need to test a few more times since we have some horizontal gesture responders that I don't want to break with this wrapper :)
> > 
> > 
> > ok no problem I can wait (dev tools are no longer accessible but that not crucial for me RN), still thx for fixing this
> 
> On master or did you check out this PR? I removed the swipe wrapper yesterday as a hotfix, so behavior should back to normal (i.e. no problems with vertical scroll - on master and at current state of this PR).

I've checked master earlier this day and this was still broken (I think one of my rebase on my branch didn't passed).
Retested now and master also works.

**Review by Jorropo — APPROVED** [review]
LGTM (I've tested it but I have no idea of how good is the code, pls get an other review :) )

**Comment by ekelen** [comment]
> LGTM (I've tested it but I have no idea of how good is the code, pls get an other review :) )

Thx! Done (informally)

**Pull request merged**
