### PR TITLE
fix: display qr code in right size on ipads

### PR DESCRIPTION
**Pull request by JohnBerd**
Signed-off-by: Xavier <lecunffxavier@gmail.com>

### CODE REVIEW

**Comment by zxxma** [comment]
Bug detected: I have a glitch when the QR Code is displayed. After the glitch, sizing is ok, but during 1sec, it's glitched.

**Review by n0izn0iz — APPROVED** [review]
LGTM, maybe move the hook to the styles package but can do in another PR

**Review by n0izn0iz — CHANGES_REQUESTED** [review]
the glitch need to be fixed

**Comment by zxxma** [comment]
Glitch fixed ✅

**Pull request merged**
