### PR TITLE
fix: typos in docs/protocol/README.md

### PR DESCRIPTION
**Pull request by mathisve**
2 of the markdown links to rendezvous-point chapter (on line 96) were broken.

### CODE REVIEW

**Review by moul — APPROVED** [review]
:heart:

**Review by aeddi — APPROVED** [review]
LGTM 👍

**Comment by aeddi** [comment]
Thanks for the fix ;)
Can amend your commit to sign it please?

**Comment by mathisve** [comment]
Woops looks like I messed this up.
Let me try again in another PR.

**Pull request closed without merging**
